
SHELL = /bin/sh
include ${PETSC_DIR}/bmake/${PETSC_ARCH}/petscconf
include ${PETSC_DIR}/bmake/common/variables
include ${DENDRO_DIR}/makeVariables
CEXT = C
CFLAGS = -DPETSC_USE_LOG 

#-D__USE_MG_INIT_TYPE2__  
#-D__USE_64_BIT_INT__

#-g -O0

include ./makefileCore

